- name: Copy /etc/network/interfaces configuration
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: Copy web server systemd service file
  copy:
    src: files/web_server.service
    dest: /etc/systemd/system/web_server.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable web server service
  systemd:
    name: web_server
    enabled: yes
    state: started

- name: Ensure web server binary is in place
  stat:
    path: /usr/local/bin/web_server
  register: web_server_binary

- name: Fail if web server binary is missing
  fail:
    msg: "web_server binary is missing at /usr/local/bin/web_server"
  when: not web_server_binary.stat.exists

